# wrangler.toml
name = "${WORKER_NAME}" # Reference from .env
main = "worker.js"
compatibility_date = "2024-02-19"

#Optional: Route configuration
#routes = [
#  { pattern = "youdomain.com", custom_domain = true }
#]

# Add this section for secrets
[vars]
HASHP = "REPLACE_ME_WITH_YOUR_HASHED_PASSOWRD"  # Keep secrets managed via Cloudflare Dashboard/Secrets
TFA = "REPLACE_ME_WITH_YOUR_2FA_KEY" # Keep secrets managed via Cloudflare Dashboard/Secrets
SALT = "webTuyo" # Keep secrets managed via Cloudflare Dashboard/Secrets
YOUR_DOMAIN="${YOUR_DOMAIN}"

[[d1_databases]]
binding = "DB" # This is the binding name used in your worker code
database_name = "${DB_NAME}" # Reference from .env
database_id = "${DATABASE_ID}" # This will be populated by the workflow env

[[kv_namespaces]]
binding = "WEBTUYOKV" # Reference from .env
id = "${KV_NAMESPACE_ID}" # This will be populated by the workflow env
# If you use wrangler preview, you might need a preview_id as well
# preview_id = "${KV_NAMESPACE_PREVIEW_ID}" # Example
